<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260814143323 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE camera (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(120) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3B1CEE055E237E06 ON camera (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3B1CEE05989D9B62 ON camera (slug)');
        $this->addSql('ALTER TABLE photo ADD camera_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE photo ADD CONSTRAINT FK_14B78418B47685CD FOREIGN KEY (camera_id) REFERENCES camera (id)');
        $this->addSql('CREATE INDEX IDX_14B78418B47685CD ON photo (camera_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE photo DROP CONSTRAINT FK_14B78418B47685CD');
        $this->addSql('DROP INDEX IDX_14B78418B47685CD');
        $this->addSql('ALTER TABLE photo DROP camera_id');
        $this->addSql('DROP TABLE camera');
    }
}
