<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260815132619 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE lens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(120) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2CDAF8C35E237E06 ON lens (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2CDAF8C3989D9B62 ON lens (slug)');
        $this->addSql('ALTER TABLE album ADD lens_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE album ADD CONSTRAINT FK_39986E434FCBBD7A FOREIGN KEY (lens_id) REFERENCES lens (id)');
        $this->addSql('CREATE INDEX IDX_39986E434FCBBD7A ON album (lens_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE lens');
        $this->addSql('ALTER TABLE album DROP CONSTRAINT FK_39986E434FCBBD7A');
        $this->addSql('DROP INDEX IDX_39986E434FCBBD7A');
        $this->addSql('ALTER TABLE album DROP lens_id');
    }
}
